name: Build/release

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Nome do programa na barra de tarefas'
        required: true
        type: string
        default: 'Minha aplicação'
      ip_proxy:
        description: 'IP do proxy (apenas IP, ex: 192.168.0.10)'
        required: true
        type: string
        default: '192.168.0.10'
      ip_app:
        description: 'IP do app (apenas IP, ex: 192.168.0.10)'
        required: true
        type: string
        default: '192.168.0.10'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          APP_NAME: ${{ inputs.app_name}}
          IP_PROXY: ${{ inputs.ip_proxy}}
          IP_APP: ${{ inputs.ip_app}}